// micro-react-appliction/src/views/home.js
import React from "react";
import { Link } from "react-router-dom";

export default class First extends React.Component {
  render() {
    return (
      <div>
        <div>micro react app home</div>
        <Link to="/first">first</Link> | <Link to="/second">second</Link>
      </div>
    );
  }
}

// micro-vue-application/src/view/home.vue
<template>
  <div>micro vue app home</div>
  <router-link name="first" to="/first">first</router-link> | 
  <router-link name="second" to="/second">second</router-link>
</template>
<script>
export default {
  mounted() {
    console.log('micro vue app home');
  },
};
</script>

<style scoped></style>
